package:
  name: rnmc-native
  version: "1.0"

source:
  url: https://github.com/danielbarter/RNMC_native/archive/2d29393f13944e829e55cc7968eb5e600d6356fd.zip
  sha256: dfdc3cdea7d9de1dae0469113daa86f271624e1cadc18cd04014ed8ee3035cea
build:
  number: 0
  skip: true  # [win]
  script: "meson setup --prefix $PREFIX builddir && cd builddir && ninja && meson install"

requirements:
  build:
    - {{ compiler("c") }}
    - meson
    - ninja
    - gsl

  host:
    - gsl

  run:
    - gsl

test:
  commands:
    - "cd builddir && meson test"

about:
  home: https://github.com/danielbarter/RNMC_native
  license: BSD-3-Clause-LBNL
  license_file: LICENSE
  summary: 'high performance reaction network simulator'

extra:
  recipe-maintainers:
    - danielbarter
