package:
  name: rnmc-native
  version: "1.7"

source:
  url: https://github.com/danielbarter/RNMC_native/archive/cb00eacac9874fd4314a623a8a9c1ac22d48efa5.zip
  sha256: 0f90896d81ba1732e17e32ffe80ff3540a944e1a572f739b9f17ba5e94a2e907
build:
  number: 0
  skip: true  # [win]
  script: "meson setup --prefix $PREFIX builddir && cd builddir && ninja && meson install"

requirements:
  build:
    - {{ compiler("c") }}
    - meson
    - ninja
    - gsl
    - sqlite

  host:
    - gsl
    - sqlite

  run:
    - gsl

test:
  commands:
    - "cd builddir && meson test"

about:
  home: https://github.com/danielbarter/RNMC_native
  license: BSD-3-Clause-LBNL
  license_file: LICENSE
  summary: 'high performance reaction network simulator'

extra:
  recipe-maintainers:
    - danielbarter
