package:
  name: rnmc-native
  version: "1.6"

source:
  url: https://github.com/danielbarter/RNMC_native/archive/f27d29f92d36aed476bb9e2507d3215e5e69b85d.zip
  sha256: e5b0db045a06d7d65f27075bc1971f55ab2545e13976327c7b0d3f80b16b46d3
build:
  number: 0
  skip: true  # [win]
  script: "meson setup --prefix $PREFIX builddir && cd builddir && ninja && meson install"

requirements:
  build:
    - {{ compiler("c") }}
    - meson
    - ninja
    - gsl
    - sqlite

  host:
    - gsl
    - sqlite

  run:
    - gsl

test:
  commands:
    - "cd builddir && meson test"

about:
  home: https://github.com/danielbarter/RNMC_native
  license: BSD-3-Clause-LBNL
  license_file: LICENSE
  summary: 'high performance reaction network simulator'

extra:
  recipe-maintainers:
    - danielbarter
