package:
  name: rnmc-native
  version: "1.8"

source:
  url: https://github.com/danielbarter/RNMC_native/archive/6c37656519f10038a546ca854825ff118c5914f9.zip
  sha256: 908a7e80962f12d63fbfbdc842bd95c2717ccabb4109af7f20ed62d513cad904
build:
  number: 0
  skip: true  # [win]
  script: "meson setup --prefix $PREFIX builddir && cd builddir && ninja && meson install"

requirements:
  build:
    - {{ compiler("c") }}
    - meson
    - ninja
    - gsl
    - sqlite

  host:
    - gsl
    - sqlite

  run:
    - gsl

test:
  commands:
    - "cd builddir && meson test"

about:
  home: https://github.com/danielbarter/RNMC_native
  license: BSD-3-Clause-LBNL
  license_file: LICENSE
  summary: 'high performance reaction network simulator'

extra:
  recipe-maintainers:
    - danielbarter
