package:
  name: rnmc-native
  version: "2.0"

source:
  url: https://github.com/danielbarter/RNMC_native/archive/5d9672167e439f04ff3b67aa267aba146b31f86b.zip
  sha256: 10e9b9945e627e7b024f62dc7a319d3c3d3ff58ee0b01c18883e84959e92d7e7
build:
  number: 0
  skip: true  # [win]
  script: "meson setup --prefix $PREFIX --buildtype=release build && cd build && ninja && meson install"

requirements:
  build:
    - {{ compiler("c") }}
    - meson
    - ninja
    - gsl
    - sqlite

  host:
    - gsl
    - sqlite

  run:
    - gsl

test:
  commands:
    - "ls"

about:
  home: https://github.com/danielbarter/RNMC_native
  license: BSD-3-Clause-LBNL
  license_file: LICENSE
  summary: 'high performance reaction network simulator'

extra:
  recipe-maintainers:
    - danielbarter
