package:
  name: rnmc-native
  version: "1.4"

source:
  url: https://github.com/danielbarter/RNMC_native/archive/f5ac3d79296fc3874fc6e2b6a3a85dce6cbc7434.zip
  sha256: 748f631e4b79f398c7aadb66c123bb870b94afe0c1d514754e9686a2b7ffab5c
build:
  number: 0
  skip: true  # [win]
  script: "meson setup --prefix $PREFIX builddir && cd builddir && ninja && meson install"

requirements:
  build:
    - {{ compiler("c") }}
    - meson
    - ninja
    - gsl

  host:
    - gsl

  run:
    - gsl

test:
  commands:
    - "cd builddir && meson test"

about:
  home: https://github.com/danielbarter/RNMC_native
  license: BSD-3-Clause-LBNL
  license_file: LICENSE
  summary: 'high performance reaction network simulator'

extra:
  recipe-maintainers:
    - danielbarter
