package:
  name: rnmc-native
  version: "1.9"

source:
  url: https://github.com/danielbarter/RNMC_native/archive/d643ec6651f325dda13fe45207ed4286f91134a0.zip
  sha256: 5b105ddcd53c335e70f3ac46724da57559b35f68bd313d74fa1031a5694e4e82
build:
  number: 1
  skip: true  # [win]
  script: "meson setup --prefix $PREFIX --buildtype=release builddir && cd builddir && ninja && meson install"

requirements:
  build:
    - {{ compiler("c") }}
    - meson
    - ninja
    - gsl
    - sqlite

  host:
    - gsl
    - sqlite

  run:
    - gsl

test:
  commands:
    - "cd builddir && meson test"

about:
  home: https://github.com/danielbarter/RNMC_native
  license: BSD-3-Clause-LBNL
  license_file: LICENSE
  summary: 'high performance reaction network simulator'

extra:
  recipe-maintainers:
    - danielbarter
